# brew command-line tools using Homebrew
# Usage: `brew bundle`

# General development stuff
brew 'bash-completion'
brew 'git'
brew 'gnupg'
brew 'pinentry-mac'
brew 'hub'
brew 'curl'
brew 'mongo-orchestration'
brew 'wget'
brew 'cloc'
brew 'mas'

# PHP packages
brew 'php'
brew 'php@7.2'
brew 'php@7.1'
brew 'composer'

# General casks
cask 'moom'
cask 'phpstorm'
cask 'slack'
cask 'toggl'
cask 'whatpulse'
cask 'whatsapp'
