# brew command-line tools using Homebrew
# Usage: `brew bundle`

tap 'alcaeus/brew'

# General development stuff
brew 'bash-completion'
brew 'git'
brew 'gnupg'
brew 'pinentry-mac'
brew 'hub'
brew 'curl'
brew 'm'
brew 'mongo-orchestration'
brew 'wget'
brew 'cloc'
brew 'mas'

# General casks
cask 'moom'
cask 'phpstorm'
cask 'slack'
cask 'toggl'
cask 'whatpulse'
cask 'whatsapp'
