#!/bin/bash

# Install homebrew
echo "Install homebrew and dependencies"
./setup-brew.sh

echo "Setup bootstrap settings"
./setup-dotfiles.sh

echo "Install app store programs"
./setup-apps.sh

echo "Configure PHP"
./setup-php.sh
