#!/bin/bash

# Install homebrew
echo "Install homebrew"
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

echo "Install brewfiles"
brew bundle --file=brew/Brewfile
brew bundle --file=brew/Caskfile

echo "Setup bootstrap settings"
./setup-dotfiles.sh

echo "Update macOS settings"
./setup-macos.sh

echo "Install app store programs"
./setup-apps.sh