#!/usr/bin/env bash

PREV_COMMIT=$1
POST_COMMIT=$2

if [[ $PREV_COMMIT == "0000000000000000000000000000000000000000" ]]; then
    return
fi

NOCOLOR='\033[0m'
REDCOLOR='\033[37;41m'

if [[ -f composer.lock ]]; then
    DIFF=`git diff --shortstat $PREV_COMMIT..$POST_COMMIT composer.lock`
    if [[ $DIFF != "" ]]; then
        echo -e "$REDCOLOR composer.lock has changed. You must run composer install$NOCOLOR"
    fi
fi